name: Backup toots
on:
  push:
  schedule:
    # At minute 4 past every 4th hour
    # https://crontab.guru/#4_*/4_*_*_*
    - cron:  '4 */4 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Get source
        uses: actions/checkout@v2
      - name: Get Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Backup toots bbelderbos
        run: python backup_toots.py bbelderbos
      - name: Backup toots pybites
        run: python backup_toots.py pybites
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Backup new toots
          file_pattern: '*.db'
